comment: false

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  range: 60...90
  round: down
  precision: 2

  status:
    project:
      default:
        target: 60%
        threshold: 0%
